### ISSUE TITLE
[Backend] Criar um banco de dados de usuário

### ISSUE THREAD

**Issue by JohnnyKamigashima** [TechRate-Lab/TR----Backend#47]
Criar um banco de dados para cadastro de usuários.

Critérios de aceite:
- email deve ser único e será quem define o usuário,  
    - Deve ter tamanho de 100 caracteres. 
    - deve ser do tipo caractere, 
    - não pode aceitar outros caracteres especiais, 
    - somente @, ponto, traço e underline.
    - Não pode aceitar espaço nem acento.
- Nome deve ser do tipo caractere, com 100 caracteres.
- Senha deve ser caractere e aceitar 100 caracteres.
-  Utilizar o Planetscale para hostear o banco de dados

**Comment by jeffbcampos** [comment]
![image](https://github.com/TechRate-Lab/TR-Backend/assets/29681473/05574072-941d-4230-9534-91c4f6646a56)
@JohnnyKamigashima tabela criada. A mesma pode ser verificada na branch teste do planet scale. Além disso, foi criado uma coluna id do tipo UUID, caso não ache necessário, refaço a tabela sem o id.

**Comment by JohnnyKamigashima** [comment]
Acho v´slido sim @jeffbcampos . Obrigado.
Tarefa encerrada!
