### ISSUE TITLE
[Token JWT] - Backend

### ISSUE THREAD

**Issue by JohnnyKamigashima** [TechRate-Lab/TR----Backend#54]
Criar uma api para gerar um token de validade de 7 dias para que o usuário possa deixar suas avaliações logadas e outras operações reservadas para usuário registrado.

Critérios:
- O token deve durar 7 dias.
- A api deve gerar a partir do email.
- Criar as rotas para acesso e busca desse token.

**Comment by jeffbcampos** [comment]
A rota de login foi criada, onde será retornado o token JWT para ser armazenado pelo Front-end(Local Storage ou Cookies).
Ele tem a duração de 7 dias e está sendo gerado com o email como valor do payload, para manipulação de rotas.
O Commit já foi realizado para a branch Development.
![image](https://github.com/TechRate-Lab/TR-Backend/assets/29681473/577a7e7d-8576-4f65-8fc5-27e544e64098)

**Comment by JohnnyKamigashima** [comment]
![Image](https://github.com/TechRate-Lab/TR-Backend/assets/50176581/4d90e279-bdd8-4e20-912f-8d385fa7219f)

Sucesso! @jeffbcampos  estou marcando como pronto!
